[package]
name = "dockerust"
version = "0.1.0"
authors = ["olvyko <olvyko@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
